#version 460

#include "CullingInclude.glsl"

layout(set = GLOBAL_SET, binding = BINDING_CAMERA_BUFFER) readonly buffer CameraDataBuffer
{
    CameraData data;
} _Camera[];

layout(set = GLOBAL_SET, binding = BINDING_INSTANCE_DATA_BUFFER, std430) readonly buffer InstanceDataBuffer
{
    InstanceData data[];
} _Instances;

layout(set = GLOBAL_SET, binding = BINDING_VISIBLE_INSTANCE_INDIRECTION_BUFFER) writeonly buffer VisibleInstanceIndirectionBuffer
{
    uint data[];
} _VisibleInstanceIndirection[];

vec3 Bbox[8] =
{
    vec3(-1.0, -1.0, -1.0),
    vec3(1.0, -1.0, -1.0),
    vec3(-1.0, 1.0, -1.0),
    vec3(-1.0, -1.0, 1.0),
    vec3(1.0, 1.0, -1.0),
    vec3(1.0, -1.0, 1.0),
    vec3(-1.0, 1.0, 1.0),
    vec3(1.0, 1.0, 1.0)
};

void TransformBBOX(mat4 transform, vec3 AabbMin, vec3 AabbMax, out vec3 outAabbMin, out vec3 outAabbMax)
{
    vec3 center = (AabbMin + AabbMax) * 0.5;
    vec3 extent = (AabbMax - AabbMin) * 0.5;

    outAabbMin = vec3(1e7);
    outAabbMax = vec3(-1e7);
    for(int i = 0; i < 8; i++)
    {
        vec4 point = vec4(center + Bbox[i] * extent, 1.0);
        point = transform * point;
        point.xyz /= point.w;
        outAabbMin = min(outAabbMin, point.xyz);
        outAabbMax = max(outAabbMax, point.xyz);
    }
}

bool TransformBBOXPerspective(mat4 transform, vec3 AabbMin, vec3 AabbMax, out vec3 outAabbMin, out vec3 outAabbMax)
{
    vec3 center = (AabbMin + AabbMax) * 0.5;
    vec3 extent = (AabbMax - AabbMin) * 0.5;

    outAabbMin = vec3(1e7);
    outAabbMax = vec3(-1e7);

    float minZ = outAabbMin.z;
    for(int i = 0; i < 8; i++)
    {
        vec4 point = vec4(center + Bbox[i] * extent, 1.0);
        point = transform * point;
        minZ = min(minZ, point.z);
        point.xyz /= point.w;
        outAabbMin = min(outAabbMin, point.xyz);
        outAabbMax = max(outAabbMax, point.xyz);
    }

    return minZ <= 0.0;
}

bool FustumCulling(CameraData camera, vec3 center, vec3 extent)
{
    for(int i = 0; i < 6; i++)
    {
        Plane plane = camera.FrustumPlanes[i];
        vec3 s = step(vec3(0.0), plane.Normal);
        vec3 point = mix(center - extent, center + extent, s);

        bool isVisible = dot(plane.Normal, point) + plane.Distance > 0.0;
        if(!isVisible) return false;
    }

    return true;
}

bool Culling(CameraData camera, InstanceData instance)
{
    vec3 wsAABBMin, wsAABBMax;
    TransformBBOX(instance.LocalToWorldMatrix, instance.AabbMin, instance.AabbMax, wsAABBMin, wsAABBMax);

    bool isVisible = FustumCulling(camera, (wsAABBMin + wsAABBMax) * 0.5, (wsAABBMax - wsAABBMin) * 0.5);

    if(isVisible)
    {
        vec3 ssAABBMin, ssAABBMax;
        bool isBehindCamera = TransformBBOXPerspective(camera.ViewProjectionMatrix, wsAABBMin, wsAABBMax, ssAABBMin, ssAABBMax);

        vec2 aabbMin = clamp(ssAABBMin.xy * 0.5 + 0.5, 0.0, 1.0);
        vec2 aabbMax = clamp(ssAABBMax.xy * 0.5 + 0.5, 0.0, 1.0);

        vec4 aabb = vec4(aabbMin.x, aabbMin.y, aabbMax.x, aabbMax.y);
        float minZ = ssAABBMin.z;
        float maxZ = ssAABBMax.z;


        uvec2 aabbSize = uvec2((aabbMax.xy - aabbMin.xy) * push.gConstants.HizSize);

        uint LOD = uint(ceil(log2(max(aabbSize.x, aabbSize.y) * 0.5)));

        vec2 lodPixelSize = vec2(1.0 / (push.gConstants.HizSize.x << LOD), 1.0 / (push.gConstants.HizSize.y << LOD));
        aabb += lodPixelSize.xyxy;

        float v0 = textureLod(uTextures[push.gConstants.HizIndex], vec2(aabb.x, aabb.w), LOD).r;
        float v1 = textureLod(uTextures[push.gConstants.HizIndex], vec2(aabb.z, aabb.w), LOD).r;
        float v2 = textureLod(uTextures[push.gConstants.HizIndex], vec2(aabb.z, aabb.y), LOD).r;
        float v3 = textureLod(uTextures[push.gConstants.HizIndex], vec2(aabb.x, aabb.y), LOD).r;

        float v = max(v0, max(v1, max(v2, v3)));

        bool isInFrontOfHiZ = minZ <= v;
        isVisible = isBehindCamera || isInFrontOfHiZ;
    }

    return isVisible;
}

layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;
void main()
{
    uint globalIndex = gl_GlobalInvocationID.x;
    if (globalIndex >= push.Constants.InstanceCount) return;

    bool isVisible = Culling(_Camera[push.gConstants.Cameras].data, _Instances.data[globalIndex]);

    if(isVisible)
    {
        uint meshIndex = _Instances.data[globalIndex].MeshIndex;
        uint countIndex = atomicAdd(_VisibleDrawIndexedIndirect[push.gConstants.VisibleDrawIndirects].data[meshIndex].instanceCount, 1);

        DrawIndexedIndirectPadded indirectCommand = _DrawIndexedIndirect.data[meshIndex];
        uint instanceIndex = indirectCommand.firstInstance + countIndex;

        _VisibleInstanceIndirection[push.gConstants.VisibleInstanceIndirections].data[instanceIndex] = globalIndex;
    }
}
