#version 460

#include "../header/GlobalIncludes.glsl"

layout(constant_id = 0) const bool USE_ORIGINAL_DEPTH = true;

struct HizGenerateConstants
{
    vec2 srcPixelSize;
    uvec2 srcSize;

    vec2 dstPixelSize;
    uvec2 dstSize;

    uint srcIndex;
    uint dstIndex;
};

layout(push_constant) uniform PushConstants
{
    CommonIndexes Indexes;
    HizGenerateConstants Constants;
} push;

layout(set = GLOBAL_SET, binding = BINDING_TEXTURES) uniform sampler2D uTextures[];
layout(set = GLOBAL_SET, binding = BINDING_HIZ_TEXTURE, r32f) uniform image2D hizTexture[];

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;
void main()
{
    if (gl_GlobalInvocationID.x >= push.Constants.dstSize.x || gl_GlobalInvocationID.y >= push.Constants.dstSize.y ) return;

    ivec2 threadID = ivec2(gl_GlobalInvocationID.xy);
    uint srcIndex = nonuniformEXT(push.Constants.srcIndex);
    uint dstIndex = nonuniformEXT(push.Constants.dstIndex);

    ivec2 baseCoords = threadID.xy * 2;
    float v0, v1, v2, v3;

    vec3 extra = vec3(0.0f);

    bool oddX = (push.Constants.srcSize.x & 1u) != 0u;
    bool oddY = (push.Constants.srcSize.y & 1u) != 0u;
    ivec2 maxCoords = ivec2(push.Constants.srcSize) - ivec2(1);

    if(USE_ORIGINAL_DEPTH)
    {
        vec2 uv = (vec2(baseCoords)+ vec2(1.0)) * push.Constants.srcPixelSize;
        vec4 v = textureGather(uTextures[srcIndex], uv);
        v0 = v.r;
        v1 = v.g;
        v2 = v.b;
        v3 = v.a;

        if (oddX && baseCoords.x == int(push.Constants.srcSize.x) - 3)
        {
            extra.x = texelFetch(uTextures[srcIndex], min(baseCoords + ivec2(2, 0), maxCoords), 0).r;
            extra.y = texelFetch(uTextures[srcIndex], min(baseCoords + ivec2(2, 1), maxCoords), 0).r;

            if (oddY && baseCoords.y == int(push.Constants.srcSize.y) - 3)
            {
                extra.z = texelFetch(uTextures[srcIndex], min(baseCoords + ivec2(2, 2), maxCoords), 0).r;
            }
        }
        else if (oddY && baseCoords.y == int(push.Constants.srcSize.y) - 3)
        {
            extra.x = texelFetch(uTextures[srcIndex], min(baseCoords + ivec2(0, 2), maxCoords), 0).r;
            extra.y = texelFetch(uTextures[srcIndex], min(baseCoords + ivec2(1, 2), maxCoords), 0).r;
        }
    }
    else
    {
        v0 = imageLoad(hizTexture[srcIndex], min(baseCoords, maxCoords)).r;
        v1 = imageLoad(hizTexture[srcIndex], min(baseCoords + ivec2(1, 0), maxCoords)).r;
        v2 = imageLoad(hizTexture[srcIndex], min(baseCoords + ivec2(1, 1), maxCoords)).r;
        v3 = imageLoad(hizTexture[srcIndex], min(baseCoords + ivec2(0, 1), maxCoords)).r;

        if (oddX && int(baseCoords.x) == push.Constants.srcSize.x-3)
        {
            extra.x =  imageLoad(hizTexture[srcIndex], min(baseCoords + ivec2(2, 0), maxCoords)).r;
            extra.y =  imageLoad(hizTexture[srcIndex], min(baseCoords + ivec2(2, 1), maxCoords)).r;
            if (oddY && int(baseCoords.y) == push.Constants.srcSize.y-3)
            {
                extra.z = imageLoad(hizTexture[srcIndex], min(baseCoords + ivec2(2, 2), maxCoords)).r;
            }
        }
        else if (oddY && int(baseCoords.y) == push.Constants.srcSize.y-3)
        {
            extra.x = imageLoad(hizTexture[srcIndex], min(baseCoords + ivec2(0, 2), maxCoords)).r;
            extra.y = imageLoad(hizTexture[srcIndex], min(baseCoords + ivec2(1, 2), maxCoords)).r;
        }
    }

    float maxDepth = max(max(max(v0, v1), max(v2, v3)), max(extra.x, max(extra.y, extra.z)));
    imageStore(hizTexture[dstIndex], threadID.xy, vec4(maxDepth, 0.0, 0.0, 0.0));
}
