#version 460

#include "../header/GlobalIncludes.glsl"

layout(constant_id = 0) const bool USE_ORIGINAL_DEPTH = true;

struct HizGenerateConstants
{
    vec2 srcPixelSize;
    uvec2 srcSize;

    vec2 dstPixelSize;
    uvec2 dstSize;

    uint srcIndex;
    uint dstIndex;
};

layout(push_constant) uniform PushConstants
{
    CommonIndexes Indexes;
    HizGenerateConstants Constants;
} push;

layout(set = GLOBAL_SET, binding = BINDING_TEXTURES) uniform sampler2D uTextures[];
layout(set = GLOBAL_SET, binding = BINDING_HIZ_TEXTURE, r32f) uniform sampler2D srcTexture[];
layout(set = GLOBAL_SET, binding = BINDING_HIZ_TEXTURE, r32f) uniform sampler2D dstTexture[];

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;
void main()
{
    if (gl_GlobalInvocationID.x >= push.Constants.srcSize.x || gl_GlobalInvocationID.y >= push.Constants.srcSize.y ) return;

    uint srcIndex = nonuniformEXT(push.Constants.srcIndex);
    uint dstIndex = nonuniformEXT(push.Constants.dstIndex);

    imageStore(dstTexture[dstIndex], ivec2(threadID), 0.5);
}
