#version 460

#include "../header/GlobalIncludes.glsl"

layout(constant_id = 0) const bool USE_ORIGINAL_DEPTH = true;

struct HizGenerateConstants
{
    vec2 srcPixelSize;
    uvec2 srcSize;

    vec2 dstPixelSize;
    uvec2 dstSize;

    uint srcIndex;
    uint dstIndex;

    uint srcMipLevel;
};

layout(push_constant) uniform PushConstants
{
    GlobalConstants gConstants;
    layout(offset=COMMON_INDEXES_OFFSET)HizGenerateConstants Constants;
} push;

layout(set = GLOBAL_SET, binding = BINDING_TEXTURES) uniform sampler2D uTextures[];
layout(set = GLOBAL_SET, binding = BINDING_HIZ_TEXTURE, r32f) uniform image2D hizTexture[];

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;
void main()
{
    HizGenerateConstants Constants = push.Constants;
    ivec2 threadID = ivec2(gl_GlobalInvocationID.xy);
    uint dstWidth = Constants.dstSize.x;
    uint dstHeight = Constants.dstSize.y;

    if (gl_GlobalInvocationID.x >= dstWidth || gl_GlobalInvocationID.y >= dstHeight) return;

    uint srcIndex = Constants.srcIndex;

    ivec2 baseCoords = ivec2(threadID.xy * 2);
    vec2 uv = vec2(baseCoords + vec2(0.5)) * Constants.srcPixelSize;
    float v0, v1, v2, v3;

    vec3 extra = vec3(0.0f);

    bool oddX = (Constants.srcSize.x & 1u) != 0u;
    bool oddY = (Constants.srcSize.y & 1u) != 0u;

    v0 = textureLodOffset(uTextures[srcIndex], uv, Constants.srcMipLevel, ivec2(0, 0)).r;
    v1 = textureLodOffset(uTextures[srcIndex], uv, Constants.srcMipLevel, ivec2(0, 1)).r;
    v2 = textureLodOffset(uTextures[srcIndex], uv, Constants.srcMipLevel, ivec2(1, 1)).r;
    v3 = textureLodOffset(uTextures[srcIndex], uv, Constants.srcMipLevel, ivec2(1, 0)).r;

    if (oddX && baseCoords.x == int(Constants.srcSize.x) - 3)
    {
        extra.x = textureLodOffset(uTextures[srcIndex], uv, Constants.srcMipLevel, ivec2(2, 0)).r;
        extra.y = textureLodOffset(uTextures[srcIndex], uv, Constants.srcMipLevel, ivec2(2, 1)).r;

        if (oddY && baseCoords.y == int(Constants.srcSize.y) - 3)
        {
            extra.z = textureLodOffset(uTextures[srcIndex], uv, Constants.srcMipLevel, ivec2(2, 2)).r;
        }
    }
    else if (oddY && baseCoords.y == int(Constants.srcSize.y) - 3)
    {
        extra.x = textureLodOffset(uTextures[srcIndex], uv, Constants.srcMipLevel, ivec2(0, 2)).r;
        extra.y = textureLodOffset(uTextures[srcIndex], uv, Constants.srcMipLevel, ivec2(1, 2)).r;
    }

    float maxDepth = max(max(max(v0, v1), max(v2, v3)), max(extra.x, max(extra.y, extra.z)));
    uint dstIndex = Constants.dstIndex;

    imageStore(hizTexture[dstIndex], threadID.xy, vec4(maxDepth, 0.0, 0.0, 0.0));
}
