#version 460

#include "../header/GlobalIncludes.glsl"

layout(constant_id = 0) const bool USE_ORIGINAL_DEPTH = true;

struct HizGenerateConstants
{
    vec2 srcPixelSize;
    uvec2 srcSize;

    vec2 dstPixelSize;
    uvec2 dstSize;

    uint srcIndex;
    uint dstIndex;
};

layout(push_constant) uniform PushConstants
{
    GlobalConstants gConstants;
    layout(offset=COMMON_INDEXES_OFFSET)HizGenerateConstants Constants;
} push;

layout(set = GLOBAL_SET, binding = BINDING_TEXTURES) uniform sampler2D uTextures[];
layout(set = GLOBAL_SET, binding = BINDING_HIZ_TEXTURE, r32f) uniform image2D hizTexture[];

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;
void main()
{
    HizGenerateConstants Constants = push.Constants;
    ivec2 threadID = ivec2(gl_GlobalInvocationID.xy);
    uint dstWidth = Constants.dstSize.x;
    uint dstHeight = Constants.dstSize.y;

    if (gl_GlobalInvocationID.x >= dstWidth || gl_GlobalInvocationID.y >= dstHeight) return;

    uint srcIndex = Constants.srcIndex;

    ivec2 baseCoords = threadID.xy * 2;
    float v0, v1, v2, v3;

    vec3 extra = vec3(0.0f);

    bool oddX = (Constants.srcSize.x & 1u) != 0u;
    bool oddY = (Constants.srcSize.y & 1u) != 0u;
    ivec2 maxCoords = ivec2(Constants.srcSize) - ivec2(1);

    if(USE_ORIGINAL_DEPTH)
    {
        //vec2 uv = (vec2(baseCoords) + vec2(1.0)) * Constants.srcPixelSize;
        //vec4 v = textureGather(uTextures[srcIndex], uv);
        v0 = texelFetch(uTextures[srcIndex], min(baseCoords + ivec2(0, 0), maxCoords), 0).r;
        v1 = texelFetch(uTextures[srcIndex], min(baseCoords + ivec2(0, 1), maxCoords), 0).r;
        v2 = texelFetch(uTextures[srcIndex], min(baseCoords + ivec2(1, 1), maxCoords), 0).r;
        v3 = texelFetch(uTextures[srcIndex], min(baseCoords + ivec2(1, 0), maxCoords), 0).r;

        if (oddX && baseCoords.x == int(Constants.srcSize.x) - 3)
        {
            extra.x = texelFetch(uTextures[srcIndex], min(baseCoords + ivec2(2, 0), maxCoords), 0).r;
            extra.y = texelFetch(uTextures[srcIndex], min(baseCoords + ivec2(2, 1), maxCoords), 0).r;

            if (oddY && baseCoords.y == int(Constants.srcSize.y) - 3)
            {
                extra.z = texelFetch(uTextures[srcIndex], min(baseCoords + ivec2(2, 2), maxCoords), 0).r;
            }

            if(gl_GlobalInvocationID.x == 5 && gl_GlobalInvocationID.y == 0)
            {
                float m = max(max(max(v0, v1), max(v2, v3)), max(extra.x, extra.y));
                ivec2 tcv0 = min(baseCoords + ivec2(0, 0), maxCoords);
                ivec2 tcv1 = min(baseCoords + ivec2(0, 1), maxCoords);
                ivec2 tcv2 = min(baseCoords + ivec2(1, 1), maxCoords);
                ivec2 tcv3 = min(baseCoords + ivec2(1, 0), maxCoords);
                ivec2 tcex = min(baseCoords + ivec2(2, 0), maxCoords);
                ivec2 tcey = min(baseCoords + ivec2(2, 1), maxCoords);
                debugPrintfEXT("FOR DEPTH %u\n",srcIndex);
                debugPrintfEXT("coords V0 = %u %u\n", tcv0.x, tcv0.y);
                debugPrintfEXT("coords V1 = %u %u\n", tcv1.x, tcv1.y);
                debugPrintfEXT("coords V2 = %u %u\n", tcv2.x, tcv2.y);
                debugPrintfEXT("coords V3 = %u %u\n", tcv3.x, tcv3.y);
                debugPrintfEXT("coords EX = %u %u\n", tcex.x, tcex.y);
                debugPrintfEXT("coords EY = %u %u\n", tcey.x, tcey.y);
                debugPrintfEXT("TEST MAX %f ---- v0 %f v1 %f v2 %f v3 %f ex %f ey %f \n", m, v0, v1, v2, v3, extra.x, extra.y);
                debugPrintfEXT("\n");
            }
        }
        else if (oddY && baseCoords.y == int(Constants.srcSize.y) - 3)
        {
            extra.x = texelFetch(uTextures[srcIndex], min(baseCoords + ivec2(0, 2), maxCoords), 0).r;
            extra.y = texelFetch(uTextures[srcIndex], min(baseCoords + ivec2(1, 2), maxCoords), 0).r;
        }
    }
    else
    {
        v0 = imageLoad(hizTexture[srcIndex], min(baseCoords, maxCoords)).r;
        v1 = imageLoad(hizTexture[srcIndex], min(baseCoords + ivec2(1, 0), maxCoords)).r;
        v2 = imageLoad(hizTexture[srcIndex], min(baseCoords + ivec2(1, 1), maxCoords)).r;
        v3 = imageLoad(hizTexture[srcIndex], min(baseCoords + ivec2(0, 1), maxCoords)).r;

        if (oddX && int(baseCoords.x) == Constants.srcSize.x-3)
        {
            extra.x =  imageLoad(hizTexture[srcIndex], min(baseCoords + ivec2(2, 0), maxCoords)).r;
            extra.y =  imageLoad(hizTexture[srcIndex], min(baseCoords + ivec2(2, 1), maxCoords)).r;
            if (oddY && int(baseCoords.y) == Constants.srcSize.y-3)
            {
                extra.z = imageLoad(hizTexture[srcIndex], min(baseCoords + ivec2(2, 2), maxCoords)).r;
            }
        }
        else if (oddY && int(baseCoords.y) == Constants.srcSize.y-3)
        {
            extra.x = imageLoad(hizTexture[srcIndex], min(baseCoords + ivec2(0, 2), maxCoords)).r;
            extra.y = imageLoad(hizTexture[srcIndex], min(baseCoords + ivec2(1, 2), maxCoords)).r;
        }
    }

    float maxDepth = max(max(max(v0, v1), max(v2, v3)), max(extra.x, max(extra.y, extra.z)));
    uint dstIndex = Constants.dstIndex;


    imageStore(hizTexture[dstIndex], threadID.xy, vec4(maxDepth, 0.0, 0.0, 0.0));
}
