#version 460

#include "../header/Global_Include.glsl"

#include "../header/Camera.glsl"
#include "../header/Material.glsl"
#include "../header/Instancing.glsl"

// layout(set = 0, binding = 0) uniform CameraDataBuffer
// {
//     CameraData _Camera;
// };

// uint _ObjectCount;

// layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;
// void main()
// {
//     uint objectIndex = gl_GlobalInvocationID.x;
//     if (objectIndex < _ObjectCount)
//     {
//         _VisibleObjectData[objectIndex] = _ObjectData[objectIndex];
//         _VisibleDrawIndexedIndirect[objectIndex] = _DrawIndexedIndirect[objectIndex];
//     }
// }

void main () {}
