#version 450

struct DrawIndexedIndirect
{
    uint indexCount;
    uint instanceCount;
    uint firstIndex;
    int vertexOffset;
    uint firstInstance;
    uint pad0[3];
};

struct ObjectData
{
    mat4 LocalToWorldMatrix;
    vec3 AabbMin;
    uint MaterialIndex;
    vec3 AabbMax;
    uint MeshId;
};

layout(std430, binding = 0) readonly buffer ObjectDataBuffer
{
    ObjectData _ObjectData[];
};

layout(std430, binding = 1) readonly buffer DrawIndexedIndirectBuffer
{
    DrawIndexedIndirect _DrawIndexedIndirect[];
};

layout(std430, binding = 2) buffer VisibleObjectDataBuffer
{
    ObjectData _VisibleObjectData[];
};

layout(std430, binding = 3) buffer VisibleDrawIndexedIndirectBuffer
{
    DrawIndexedIndirect _VisibleDrawIndexedIndirect[];
};

uint _ObjectCount;

layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;
void main()
{
    uint objectIndex = gl_GlobalInvocationID.x;
    if (objectIndex < _ObjectCount)
    {
        _VisibleObjectData[objectIndex] = _ObjectData[objectIndex];
        _VisibleDrawIndexedIndirect[objectIndex] = _DrawIndexedIndirect[objectIndex];
    }
}
