#version 460

#include "../header/Global_Include.glsl"

#include "../header/Camera.glsl"
#include "../header/Material.glsl"
#include "../header/Instancing.glsl"

struct CullingConstants
{
    uint ObjectCount;
};

layout(push_constant) uniform PushConstants
{
    BufferIndexes bufferIndex;
    CullingConstants _CullingConstants;
} push;

layout(set = GLOBAL_SET, binding = BINDING_CAMERA_BUFFER) readonly buffer CameraDataBuffer
{
    CameraData data;
} _Camera[];

layout(set = GLOBAL_SET, binding = STATIC_BINDING_INSTANCE_DATA_BUFFER, std430) readonly buffer InstanceDataBuffer
{
    InstanceData data[];
} _Instances;


layout(set = GLOBAL_SET, binding = STATIC_BINDING_DRAW_INDIRECT_BUFFER, std430) readonly buffer DrawIndirectBuffer
{
    DrawIndexedIndirectPadded data[];
} _DrawIndexedIndirect;

layout(set = GLOBAL_SET, binding = BINDING_VISIBLE_INSTANCE_DATA_BUFFER) writeonly buffer VisibleInstanceDataBuffer
{
    InstanceData data[];
} _VisibleInstanceData[];

layout(set = GLOBAL_SET, binding = BINDING_VISIBLE_DRAW_INDIRECT_BUFFER) writeonly buffer VisibleDrawIndirectBuffer
{
    DrawIndexedIndirectPadded data[];
} _VisibleDrawIndexedIndirect[];

layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

void main()
{
    uint objectIndex = gl_GlobalInvocationID.x;
    if (objectIndex >= push._CullingConstants.ObjectCount) return;

    uint cameraBufferIndex = nonuniformEXT(push.bufferIndex.Cameras);
    uint visibleInstanceDataBufferIndex = nonuniformEXT(push.bufferIndex.VisibleInstanceDatas);
    uint visibleDrawIndirectBufferIndex = nonuniformEXT(push.bufferIndex.VisibleDrawIndirects);

    _VisibleInstanceData[visibleInstanceDataBufferIndex].data[objectIndex] = _Instances.data[objectIndex];
    _VisibleDrawIndexedIndirect[visibleDrawIndirectBufferIndex].data[objectIndex] = _DrawIndexedIndirect.data[objectIndex];
}
